spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/news_service_db
    username: postgres
    password: postgres
    hikari:
      schema: news_schema
      connection-ini-sql: CREATE SCHEMA IF NOT EXISTS news_schema
      connection-timeout: 10000


app:
  check-client-api-header: false
  client-api-key: 12345
